### ISSUE TITLE
`\r` causes diff in identical texts

### ISSUE THREAD

**Issue by tardigrde** [chrisjsewell/pytest-notebook#13]
I'm testing a CLI application with pytest-notebook. I have two identical outputs, still I get differences (an extra carriage return):
- in variable `nb_initial_replace` I get:
`some text\n`
- in variable `nb_final_replace` I get:
`some text\r\n`.

I suspect the reason behind this is that I use bash commands in the notebook cells to invoke the CLI methods like this:
```
!./app.py $some $args
```

Is there a way to e.g. avoid diffing characters like this? Is it an option to strip the output of the cells before diffing? Would that break existing or future features?

Or do you have any suggestion to work around this? Thanks in advance.

**Comment by tardigrde** [comment]
I will just quickly answer my question. I made the rookie mistake of not reading through the fixture class' interface. There is a `diff replace` attribute, which I used to clear the `\r` characters.

For anyone in the future:
`fixture.diff_replace =(('/cells/*/outputs', '\\r', ''),)`

Thanks for your work!

**Comment by chrisjsewell** [comment]
always happy when someone answers their own question thanks 😆
