### ISSUE TITLE
Can I skip specific cells in a Jupyter?

### ISSUE THREAD

**Issue by TommasoBendinelli** [chrisjsewell/pytest-notebook#14]
Hello,
I would like to be able to just run specific cells? I would like to skip cells where execution time takes more than 5 sec

**Comment by TommasoBendinelli** [comment]
I tried by placing skip in the cell metadata but it does not work apparently

**Comment by chrisjsewell** [comment]
this is very similar to https://github.com/executablebooks/jupyter-book/issues/833.
So no not at the moment I'm afraid, but when we implement it there, I can basically copy it over to here 😄

**Comment by TommasoBendinelli** [comment]
Alright thank you! Your pluging seems really interesting, but I think this is quite an important feature. For instance with plotly graphs the difftool does not work properly, hence would be nice to skip any cell with plotly graphs inside

**Comment by TommasoBendinelli** [comment]
For now I will just  ignore the output of those cells, but it makes running testing unnecessary heavy

**Comment by chrisjsewell** [comment]
Heya, from pytest-notebook>=0.7 onwards, and with nbclient >=5.5, you should now be able to use  the `skip-execution` tag (see https://nbclient.readthedocs.io/en/latest/changelog.html?highlight=skip#id10)
