### ISSUE TITLE
TypeError: 'coroutine' object is not subscriptable

### ISSUE THREAD

**Issue by qci-amos** [chrisjsewell/pytest-notebook#17]
This dependency pin appears to now be in conflict with the latest `jupyter-client` 7.0.0:
https://github.com/chrisjsewell/pytest-notebook/blob/40381be0963a8866d1a46994595844bbfb4e66c1/setup.py#L26

see https://github.com/jupyter/jupyter_client/issues/637

**Comment by qci-amos** [comment]
may be blocked by https://github.com/chrisjsewell/pytest-notebook/issues/10?

**Comment by chrisjsewell** [comment]
Now fixed in pytest-notebook 0.7.0 (nbconvert is no longer a dependency)
