### ISSUE TITLE
Replace `pkg_resources` with `importlib_metadata`

### ISSUE THREAD

**Issue by ErikBjare** [chrisjsewell/pytest-notebook#44]
The plugin caused my tests to not start, as `pkg_resources` was not available (no setuptools).

It's used for `pkg_resources.iter_entry_points()`: https://github.com/search?q=repo%3Achrisjsewell%2Fpytest-notebook%20pkg_resources&type=code

It's fair to say it is deprecated (and unavailable without `setuptools`), and replaced by `importlib`.

However, the `importlib_metadata` package is needed to backport it for Python <3.10 (`importlib.metadata.entry_points` was added in 3.10).

Here's a couple random issues describing why: 

 - https://github.com/pypa/pip/issues/7413
 - https://git.smhi.se/climix/climix/-/issues/225
   - PR: https://git.smhi.se/climix/climix/-/merge_requests/165/diffs

**Comment by sphuber** [comment]
I addressed this problem in this PR: https://github.com/chrisjsewell/pytest-notebook/pull/41/files
Except the tests are failing for other reasons. I opened another PR to address those as well: https://github.com/chrisjsewell/pytest-notebook/pull/42
There are just a few outstanding failures that I do not know how to address and would need support from @chrisjsewell

**Comment by chrisjsewell** [comment]
closed in #41
