### ISSUE TITLE
Incompatible with nbdime version 4.0.0+

### ISSUE THREAD

**Issue by renonat** [chrisjsewell/pytest-notebook#59]
## Issue

`pytest-notebook` is incompatible with `nbdime>=4.0.0` as `nbdime.diffing.generic.diff` dropped the `predicates` keyword argument. 

## Notes
- `nbdime` PR: https://github.com/jupyter/nbdime/pull/639
- `pytest-notebook` usage: https://github.com/chrisjsewell/pytest-notebook/blob/413609804db1568d0dc9024902778be8171d1a2a/pytest_notebook/diffing.py#L82C10-L82C10

## Stack Trace
```
   def diff_notebooks(
        initial: NotebookNode, final: NotebookNode, initial_path: str = ""
    ) -> List[DiffEntry]:
        """Compare two notebooks.
    
        This is a simplified version of ``nbdime.diff_notebooks()``, where we replace
        ``nbdime.diff_sequence_multilevel()`` with ``diff_sequence_simple()``
        to diff the cell and output lists.
        ``diff_sequence_multilevel`` use 'snakes' computation, to guess where cells have
        been inserted/removed. However, this can lead to longer diffs, where cells with
        changed outputs are assigned as removed/inserted, rather than simply modified.
        Moreover, since we are comparing the same notebook before/after execution,
        we shouldn't need to worry about insertions.
    
        """
>       return diff(
            initial,
            final,
            path=initial_path,
            predicates=defaultdict2(lambda: [operator.__eq__], {}),
            differs=defaultdict2(
                lambda: diff,
                {
                    "/cells": diff_sequence_simple,
                    "/cells/*": diff,
                    "/cells/*/outputs": diff_sequence_simple,
                    "/cells/*/outputs/*": diff_single_outputs,
                    "/cells/*/attachments": diff_attachments,
                },
            ),
        )
E       TypeError: diff() got an unexpected keyword argument 'predicates'
/usr/local/lib/python3.11/site-packages/pytest_notebook/diffing.py:78: TypeError
```

**Comment by cpascual** [comment]
I just had the same issue breaking my CI.

As a workaround a pinned `nbdime==3.2.1`  in my project until this is solved in `pytest-notebooks`

**Comment by chrisjsewell** [comment]
Thanks for reporting. I probably won't have time to look at this straight away, so any PRs or suggestions on how to fix would be appreciated!

**Comment by cpascual** [comment]
If you want, I can make a quick PR just limiting the nbdime depend to `<=4` as a workaround to prevent other people being hit by this until a proper fix is done

**Comment by cpascual** [comment]
I just created the PR #60 .
Its workflow is pending approval for running

**Comment by krassowski** [comment]
> suggestions on how to fix would be appreciated!

well, that should be rather straightforward since now instead of `predicates` one should pass `config` which includes predicates. See the diff from https://github.com/jupyter/nbdime/pull/639, in particular:

```diff
-    predicates = defaultdict(lambda: [operator.__eq__], {
-        '/': [lambda a, b: a['id'] == b['id']],
-    })
+    config = DiffConfig(
+        predicates=defaultdict(lambda: [operator.__eq__], {
+            '/': [lambda a, b: a['id'] == b['id']],
+        })
+    )

-    ld = diff(b, l, path="", predicates=predicates)
+    ld = diff(b, l, path="", config=config)
```

Alternatively, _nbdime_ could be patched for backward compatibility re-adding predicates as an optional, deprecated argument (which cannot be passed when config is passed).

**Comment by amotl** [comment]
Dear Reno, Carlos, and Michał,

thank you very much for your reports and suggestions how to fix this problem. We just submitted GH-62 to make `pytest-notebook` compatible with `nbdime>=4`.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Thanks for the quick release, Chris. Cheers!
